import { Navbar } from '../Navbar'
import styles from './MainLayout.module.css'
import Head from 'next/head'
import { Inter } from "next/font/google";
import { FC, PropsWithChildren } from 'react';


const inter = Inter({ subsets: ["latin"] });

export const MainLayout: FC<PropsWithChildren> = ({ children}) => {
  return (
    <div>
      <Head>
        <title>Curso Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={`${styles.main} ${inter.className}`}>
       {children}
      </main>
    </div>
  )
}
